name: Deploy (DEV)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm run test
          
  deploy-to-dev:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch secrets from Vault
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.andremisdary.com:8200
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          exportEnv: true
          secrets: |
            kv/data/shared DOCKERHUB_USERNAME | DOCKERHUB_USERNAME;
            kv/data/shared DOCKERHUB_ACCESS_TOKEN | DOCKERHUB_TOKEN;
            kv/data/frontend DROPLET_IP | DROPLET_IP;
            kv/data/frontend SSH_PRIVATE_KEY | SSH_PRIVATE_KEY;

      - name: Build commit image
        run: sudo docker build --build-arg BUILD_ENV="dev" -t amisdary/personal-website-dev:${{ github.sha }} .
    
      - name: Tag commit image as latest
        run: sudo docker tag amisdary/personal-website-dev:${{ github.sha }} amisdary/personal-website-dev:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Push Docker images to Docker Hub 
        run: |
          docker push amisdary/personal-website-dev:${{ github.sha }}
          docker push amisdary/personal-website-dev:latest

      - name: Copy docker and nginx files to droplet
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.DROPLET_IP }}
          username: deploy
          key: ${{ env.SSH_PRIVATE_KEY }}
          source: docker-compose.yml
          target: "~/personal-website"

      - name: Deploy to DigitalOcean droplet
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ env.DROPLET_IP }}
          username: deploy
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            cd ~/personal-website
            docker pull amisdary/personal-website-dev:latest
            docker compose up -d --remove-orphans personal-website-dev